---
- name: Play for Variables Lesson
  hosts: all
  become: yes

  vars:
    message1: Privet
    message2: World
    secret: Password

  tasks:
    - name: Print Secret variables
      debug:
        var: secret

    - debug:
        msg: Secret word - {{secret}}

    - debug:
        msg: Owner is {{owner}}

    - set_fact: full_message='{{message1}} {{message2}} {{owner}}'

    - debug:
        var: full_message

    - debug:
        var: ansible_distribution

    - shell: uptime
      register: results

    - debug:
        var: results.stdout